server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/santander-dev-week
    username: postgres
    password: docker
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Prjeto bootcamp santander
